apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: default
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/kjedynak00
  services.yaml: |
    - Applications:
        - OpenWebUI:
            icon: open-webui.png
            href: https://ai.kacperjedynak.pl/
            description: My Priv AI
        - Kavita:
            icon: kavita.png
            href: https://kavita.kacperjedynak.pl/
            description: My Books
        - BentoPDF:
            icon: bentopdf.png
            href: https://pdf.kacperjedynak.pl/
            description: My PDF editor
        - Mealie:
            icon: mealie.png
            href: https://meal.kacperjedynak.pl/
            description: My Recipe Manager

    - Lab Management:
        - Proxmox:
            icon: proxmox.png
            href: https://proxmox.kacperjedynak.pl/
            description: Manage your VMs and containers.
        - Beszel:
            icon: beszel.png
            href: https://beszel.kacperjedynak.pl/
            description: Monitor your cluster and resources.
        - ProxMenux:
            icon: proxmenux.png
            href: https://proxmenux.kacperjedynak.pl/
            description: Manage your Proxmox cluster with ease.

    - My Third Group:
        - My Third Service:
            href: http://localhost/
            description: Homepage is 😎
        - Plex:
            icon: plex.png
            href: https://plex.my.host
            description: Watch movies and TV shows.

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
