apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  labels:
    app: homepage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
      - name: homepage
        image: gethomepage/homepage:latest
        resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: homepage-config-volume
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: homepage-config-volume
        configMap:
          name: homepage-config
          items:
            - key: homepage-config.json
              path: config.json

---
apiVersion: v1
kind: Service
metadata:
  name: homepage-svc
spec:
  selector:
    app: homepage
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31300
  type: NodePort