apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  labels:
    app: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
      - name: homepage
        image: gethomepage/homepage:latest
        resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
        env:
          - name: HOST
            value: "192.168.100.14"
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /api/healthcheck
            port: http
          initialDelaySeconds: 10
          periodSeconds: 15
        volumeMounts:
          - mountPath: /app/config/custom.js
            name: homepage-config
            subPath: custom.js
          - mountPath: /app/config/custom.css
            name: homepage-config
            subPath: custom.css
          - mountPath: /app/config/bookmarks.yaml
            name: homepage-config
            subPath: bookmarks.yaml
          - mountPath: /app/config/docker.yaml
            name: homepage-config
            subPath: docker.yaml
          - mountPath: /app/config/kubernetes.yaml
            name: homepage-config
            subPath: kubernetes.yaml
          - mountPath: /app/config/services.yaml
            name: homepage-config
            subPath: services.yaml
          - mountPath: /app/config/settings.yaml
            name: homepage-config
            subPath: settings.yaml
          - mountPath: /app/config/widgets.yaml
            name: homepage-config
            subPath: widgets.yaml
          - mountPath: /app/config/logs
            name: logs
      volumes:
      - name: homepage-config
        configMap:
          name: homepage
      - name: logs
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: homepage-svc
spec:
  selector:
    app: homepage
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31300
  type: NodePort