apiVersion: v1
kind: PersistentVolume
metadata:
  name: mealie-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /data/mealie/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: mealie-pv
  resources:
    requests:
      storage: 5Gi

# Deployment for Mealie
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:latest
          ports:
            - containerPort: 9000
          env:
            - name: ALLOW_SIGNUP
              value: "true"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Warsaw
            - name: MAX_WORKERS
              value: "1"
            - name: WEB_CONCURRENCY
              value: "1"
            - name: BASE_URL
              value: http://192.168.100.14
            - name: MEALIE_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: mealie-secrets
                  key: MEALIE_ADMIN_USER
            - name: MEALIE_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mealie-secrets
                  key: MEALIE_ADMIN_PASSWORD
          volumeMounts:
            - name: mealie-data
              mountPath: /app/data
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-pvc

# Service to expose Mealie
---
apiVersion: v1
kind: Service
metadata:
  name: mealie
spec:
  selector:
    app: mealie
  ports:
    - port: 80
      targetPort: 9000
      nodePort: 30925
  type: NodePort