---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kavita-config-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/kavita/config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kavita-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/kavita/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kavita-books-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyOnce
  nfs:
    server: 192.168.100.91
    path: /volume1/NAS/kavita_books
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-books-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kavita
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kavita
  template:
    metadata:
      labels:
        app: kavita
    spec:
      containers:
      - name: kavita
        image: lscr.io/linuxserver/kavita:latest
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: kavita-secrets  # Wszystko z tego Secret!
        volumeMounts:
        - name: config
          mountPath: /config
        - name: data
          mountPath: /data
        - name: books
          mountPath: /books
          readOnly: true
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: kavita-config-pvc
      - name: data
        persistentVolumeClaim:
          claimName: kavita-data-pvc
      - name: books
        persistentVolumeClaim:
          claimName: kavita-books-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: kavita
spec:
  type: NodePort
  selector:
    app: kavita
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
